name: 'Setup EleasticSearch'
description: 'Setup EleasticSearch instance'
author: 'digitonic'
branding:
  icon: 'database'
  color: 'green'
inputs:
  elasticsearch-version:
    description: 'Version of EleasticSearch to use'
    required: false
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.elasticsearch-version }}